### PR TITLE
feat(isNullOrWhitespace): Add isNullOrWhitespace function

### PR DESCRIPTION
**Pull request by aleury**
Here's a PR for [#45](https://github.com/eggheadio-github/stack-overflow-copy-paste/issues/45).

### CODE REVIEW

**Comment by aleury** [comment]
Looks I committed before I made fixes for eslint. I'll get the PR updated.

**Comment by kentcdodds** [comment]
Perfect! Great work!

**Comment by aleury** [comment]
Thanks for your help @kentcdodds! I really appreciate the work you do to help bring new comers into the world of open source.

**Comment by kentcdodds** [comment]
Sure thing! Welcome to the community!

**Pull request merged**
