### PR TITLE
my first commit

### PR DESCRIPTION
**Pull request by profoundhub**
WIP: Cannot get Coverage quite there ... .

Noticed a lot of errors along the way, here are some:

(node:11348) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrad
e your codebase automatically.
(node:7072) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrade
 your codebase automatically.
(node:6796) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrade
 your codebase automatically.
(node:12388) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrad
e your codebase automatically.
(node:10684) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrad
e your codebase automatically.
(node:10944) DeprecationWarning: DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/avajs/ava-codemods to help upgrad
e your codebase automatically.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ah! Thanks for reporting this. I'll try to get it fixed soon.

**Comment by kentcdodds** [comment]
Alrighty! I've fixed everything up and you should be good to go now! Let me know if you have any more trouble :D

**Comment by kentcdodds** [comment]
You'll want to make sure to [update your fork](http://stackoverflow.com/a/7244456/971592) or delete it and create it over again. Thanks!

**Comment by profoundhub** [comment]
Thanks Kent, I will try it out later today.

**Pull request closed without merging**
