### PR TITLE
feat(flatten): Implement variable arity for flatten function, add test

### PR DESCRIPTION
**Pull request by davidrayoussef**
First PR. Added implementation for flatten function to accept multiple arrays, and added a test with multiple parameters.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Fantastic. This is great. Thank you for your contribution! Could you update the commit message to more closely follow [the standard](https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md)? The subject is too long and it should state that it's closing #17
Thanks!

**Comment by davidrayoussef** [comment]
No, thank you Kent for helping me get my first green. But can you help me update the commit message? Should I do an npm run commit again? Because I'm getting an error since there are no changes. Or should I do a force push, or can I edit it right in Github?

**Comment by kentcdodds** [comment]
In this scenario, the easiest would be to run `git reset HEAD^` then do `git diff` to make sure the changes are what you expect, then run `git add -A` and run `npm run commit` or you could create your message by hand with `git commit`

Let me know if you need more direction!

**Comment by davidrayoussef** [comment]
Okay cool. I think I got it right this time, but had to do a force push. Let me know if there's an issue.

**Comment by kentcdodds** [comment]
Perfect! Thank you! And congrats on your first pull request!

**Pull request merged**
