### PR TITLE
WIP: Getting eslint errors because of linebreaks

### PR DESCRIPTION
**Pull request by kelvinatorr**
Getting eslint errors on all the other files in src

eslint

Is it because I am on Windows?

I am not getting them on test/sort-objects-array.test.js and src/sort-objects-array.js because I changed my editor to use LF.

What should I do?

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi @kelvinatorr!
This is really common. You may need to configure your local `git` install to treat line endings properly: https://help.github.com/articles/dealing-with-line-endings/#platform-windows

Once you do that, I recommend re-cloning the repository.

Let me know if you need help.

**Comment by kelvinatorr** [comment]
Thanks @kentcdodds 

Running 

`git config --global core.autocrlf false`

fixed the linebreaks issue. But eslint gave an error for a missing trailing comma so I fixed that and made a new commit.

**Comment by kentcdodds** [comment]
This is perfect! Thank you for your contribution :+1:

**Comment by kelvinatorr** [comment]
Thanks for making the videos and helping me practice Kent! I hope other maintainers are are friendly and helpful as you are.

**Pull request merged**
