### PR TITLE
feat(cube): Add cube function

### PR DESCRIPTION
**Pull request by akoliyot**
Add a function to find the cube of a number.

### CODE REVIEW

**Comment by akoliyot** [comment]
@kentcdodds It's ready to go :)

**Comment by kentcdodds** [comment]
Well done :)

**Comment by akoliyot** [comment]
Thank you so much for your time and effort too! :)
Should I close the issue I created on eggheadio-github/stack-overflow-copy-paste now?

**Comment by kentcdodds** [comment]
Yeah, go ahead and do that. Normally in the commit message or pull request comment you can use the phrase "Closes #117” and GitHub will lose it automatically. 👍

**Pull request merged**
